import ping from "./commands/tools/ping.js";
import start from "./commands/tools/start.js";
import history from "./commands/ai-chat/history.js";
import reset from "./commands/ai-chat/reset.js";
import ai from "./commands/ai-chat/ai.js";
import github from "./commands/tools/github.js";
import setver from "./commands/tools/setver.js";
import encrypt from "./commands/tools/enc.js";
import decrypt from "./commands/tools/dec.js";
import help from "./commands/tools/help.js";
import format from "./commands/tools/format.js";
import resetver from "./commands/tools/resetver.js";
import tagall from "./commands/tools/tagall.js";
import cekmodel from "./commands/ai-chat/cekmodel.js";
import model from "./commands/ai-chat/model.js";
import historyall from "./commands/owner/historyall.js";
import resetall from "./commands/owner/resetall.js";
import btc from "./commands/crypto/btc.js";

export const registerHandlers = (bot) => {
  ping(bot);
  start(bot);
  history(bot);
  reset(bot);
  model(bot);
  cekmodel(bot);
  historyall(bot);
  resetall(bot);
  tagall(bot);
  btc(bot);
  github(bot);
  setver(bot);
  encrypt(bot);
  decrypt(bot);
  help(bot);
  format(bot);
  resetver(bot);
  ai(bot);
};
